begin;

create table public.ninety_day_cycles (
  id bigint generated by default as identity primary key,
  name text not null check (length(btrim(name)) between 1 and 120),
  starts_on date not null,
  ends_on date not null,
  timezone text not null default 'America/Edmonton'
    check (length(btrim(timezone)) between 1 and 80),
  status text not null default 'draft'
    check (status in ('draft', 'active', 'completed')),
  active_system_node_id bigint references public.content_nodes(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on = starts_on + 89)
);

create unique index ninety_day_cycles_one_active_idx
  on public.ninety_day_cycles ((true))
  where status = 'active';

create table public.ninety_day_cycle_systems (
  cycle_id bigint not null references public.ninety_day_cycles(id) on delete cascade,
  node_id bigint not null references public.content_nodes(id) on delete restrict,
  position smallint not null check (position between 1 and 8),
  created_at timestamptz not null default now(),
  primary key (cycle_id, node_id),
  unique (cycle_id, position)
);

alter table public.ninety_day_cycles
  add constraint ninety_day_cycles_active_system_in_cycle_fk
  foreign key (id, active_system_node_id)
  references public.ninety_day_cycle_systems(cycle_id, node_id)
  deferrable initially deferred;

create table public.ninety_day_cycle_users (
  cycle_id bigint not null references public.ninety_day_cycles(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  ended_at timestamptz,
  outcome text check (outcome is null or outcome in ('promoted', 'removed', 'transferred')),
  primary key (cycle_id, user_id),
  check ((ended_at is null and outcome is null) or (ended_at is not null and outcome is not null))
);

create unique index ninety_day_cycle_users_one_open_enrollment_idx
  on public.ninety_day_cycle_users(user_id)
  where ended_at is null;

create table public.ninety_day_cycle_meetings (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null references public.ninety_day_cycles(id) on delete cascade,
  title text not null default 'Weekly group call'
    check (length(btrim(title)) between 1 and 160),
  starts_at timestamptz not null,
  ends_at timestamptz,
  join_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cycle_id, starts_at),
  check (ends_at is null or ends_at > starts_at),
  check (join_url is null or join_url ~ '^https?://')
);

create or replace function public.validate_ninety_day_system()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
begin
  if not exists (
    select 1
    from public.content_nodes node
    where node.id = new.node_id
      and node.state = 'published'
      and node.slug is not null
      and node.node_type in ('lesson', 'chapter', 'playlist')
  ) then
    raise exception '90-day systems must be published, linked learning nodes'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create trigger ninety_day_cycle_systems_validate
before insert or update of node_id on public.ninety_day_cycle_systems
for each row execute function public.validate_ninety_day_system();

create or replace function public.validate_ninety_day_cycle_activation()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  system_count integer;
begin
  new.updated_at := now();

  if new.status = 'active' then
    select count(*) into system_count
    from public.ninety_day_cycle_systems
    where cycle_id = new.id;

    if system_count <> 8 then
      raise exception 'An active 90-day cycle must have exactly eight systems'
        using errcode = '23514';
    end if;

    if new.active_system_node_id is null then
      raise exception 'An active 90-day cycle must have a current system'
        using errcode = '23514';
    end if;
  end if;

  return new;
end;
$$;

create trigger ninety_day_cycles_validate_activation
before insert or update
on public.ninety_day_cycles
for each row execute function public.validate_ninety_day_cycle_activation();

create or replace function public.touch_ninety_day_meeting()
returns trigger
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger ninety_day_cycle_meetings_touch
before update on public.ninety_day_cycle_meetings
for each row execute function public.touch_ninety_day_meeting();

create or replace function public.enroll_ninety_day_user(
  p_user_id uuid,
  p_cycle_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  ninety_day_role_id bigint;
  member_role_id bigint;
  cycle_status text;
begin
  select status into cycle_status
  from public.ninety_day_cycles
  where id = p_cycle_id;

  if cycle_status is null or cycle_status not in ('draft', 'active') then
    raise exception 'A draft or active 90-day cycle is required' using errcode = 'P0001';
  end if;

  if not exists (select 1 from public.profiles where id = p_user_id) then
    raise exception 'User profile not found' using errcode = 'P0001';
  end if;

  select id into ninety_day_role_id from public.roles where code = 'ninety-day-user';
  select id into member_role_id from public.roles where code = 'user';

  if ninety_day_role_id is null or member_role_id is null then
    raise exception 'Required role definition is missing' using errcode = 'P0001';
  end if;

  if exists (
    select 1 from public.user_roles
    where user_id = p_user_id and role_id = member_role_id
  ) then
    raise exception 'A full member cannot be enrolled as a 90-day user'
      using errcode = 'P0001';
  end if;

  if exists (
    select 1 from public.ninety_day_cycle_users
    where user_id = p_user_id and ended_at is null and cycle_id <> p_cycle_id
  ) then
    raise exception 'User already has an open 90-day cycle enrollment'
      using errcode = 'P0001';
  end if;

  insert into public.user_roles(user_id, role_id)
  values (p_user_id, ninety_day_role_id)
  on conflict (user_id, role_id) do nothing;

  insert into public.ninety_day_cycle_users(cycle_id, user_id)
  values (p_cycle_id, p_user_id)
  on conflict (cycle_id, user_id) do update
    set ended_at = null, outcome = null, enrolled_at = now();

  return true;
end;
$$;

create or replace function public.configure_ninety_day_cycle(
  p_cycle_id bigint,
  p_name text,
  p_starts_on date,
  p_timezone text,
  p_status text,
  p_system_node_ids bigint[],
  p_active_system_node_id bigint,
  p_actor_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  node_id bigint;
  node_position integer := 0;
begin
  if not exists (select 1 from public.ninety_day_cycles where id = p_cycle_id) then
    raise exception '90-day cycle not found' using errcode = 'P0001';
  end if;

  if p_status not in ('draft', 'active', 'completed') then
    raise exception 'Invalid 90-day cycle status' using errcode = 'P0001';
  end if;

  if p_system_node_ids is null or cardinality(p_system_node_ids) > 8 then
    raise exception 'A 90-day cycle can contain at most eight systems' using errcode = 'P0001';
  end if;

  if cardinality(p_system_node_ids) <> (
    select count(distinct value) from unnest(p_system_node_ids) as requested(value)
  ) then
    raise exception '90-day cycle systems must be unique' using errcode = 'P0001';
  end if;

  if p_active_system_node_id is not null
    and not (p_active_system_node_id = any(p_system_node_ids)) then
    raise exception 'The current system must be one of the cycle systems' using errcode = 'P0001';
  end if;

  delete from public.ninety_day_cycle_systems where cycle_id = p_cycle_id;

  foreach node_id in array p_system_node_ids loop
    node_position := node_position + 1;
    insert into public.ninety_day_cycle_systems(cycle_id, node_id, position)
    values (p_cycle_id, node_id, node_position);
  end loop;

  update public.ninety_day_cycles
  set name = btrim(p_name),
      starts_on = p_starts_on,
      ends_on = p_starts_on + 89,
      timezone = btrim(p_timezone),
      status = p_status,
      active_system_node_id = p_active_system_node_id,
      updated_by = p_actor_id
  where id = p_cycle_id;

  return true;
end;
$$;

-- Replace the role-only implementation from the preceding migration so the
-- enrollment history closes in the same transaction as the access swap.
create or replace function public.promote_ninety_day_user(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  ninety_day_role_id bigint;
  member_role_id bigint;
  has_ninety_day_role boolean;
  has_member_role boolean;
begin
  select id into ninety_day_role_id from public.roles where code = 'ninety-day-user';
  select id into member_role_id from public.roles where code = 'user';

  if ninety_day_role_id is null or member_role_id is null then
    raise exception 'Required role definition is missing' using errcode = 'P0001';
  end if;

  select exists (
    select 1 from public.user_roles
    where user_id = p_user_id and role_id = ninety_day_role_id
  ) into has_ninety_day_role;

  select exists (
    select 1 from public.user_roles
    where user_id = p_user_id and role_id = member_role_id
  ) into has_member_role;

  if not has_ninety_day_role then
    if has_member_role then return false; end if;
    raise exception 'User is not a ninety-day user' using errcode = 'P0001';
  end if;

  insert into public.user_roles(user_id, role_id)
  values (p_user_id, member_role_id)
  on conflict (user_id, role_id) do nothing;

  delete from public.user_roles
  where user_id = p_user_id and role_id = ninety_day_role_id;

  update public.ninety_day_cycle_users
  set ended_at = now(), outcome = 'promoted'
  where user_id = p_user_id and ended_at is null;

  return true;
end;
$$;

-- Keep the fixed course available even if its audience is changed from public
-- to limited later. Application course listing additionally hides every other
-- course from 90-day-only accounts.
insert into public.content_node_roles(node_id, role_id)
select node.id, role.id
from public.content_nodes node
cross join public.roles role
where node.slug = 'set-your-compass'
  and node.node_type = 'course'
  and role.code = 'ninety-day-user'
on conflict (node_id, role_id) do nothing;

alter table public.ninety_day_cycles enable row level security;
alter table public.ninety_day_cycle_systems enable row level security;
alter table public.ninety_day_cycle_users enable row level security;
alter table public.ninety_day_cycle_meetings enable row level security;

revoke all on table public.ninety_day_cycles, public.ninety_day_cycle_systems,
  public.ninety_day_cycle_users, public.ninety_day_cycle_meetings
  from public, anon, authenticated;
grant all on table public.ninety_day_cycles, public.ninety_day_cycle_systems,
  public.ninety_day_cycle_users, public.ninety_day_cycle_meetings
  to service_role;

revoke all on sequence public.ninety_day_cycles_id_seq,
  public.ninety_day_cycle_meetings_id_seq
  from public, anon, authenticated;
grant all on sequence public.ninety_day_cycles_id_seq,
  public.ninety_day_cycle_meetings_id_seq
  to service_role;

alter function public.validate_ninety_day_system() owner to postgres;
alter function public.validate_ninety_day_cycle_activation() owner to postgres;
alter function public.touch_ninety_day_meeting() owner to postgres;
alter function public.enroll_ninety_day_user(uuid, bigint) owner to postgres;
alter function public.configure_ninety_day_cycle(bigint, text, date, text, text, bigint[], bigint, uuid)
  owner to postgres;
alter function public.promote_ninety_day_user(uuid) owner to postgres;

revoke all on function public.validate_ninety_day_system(),
  public.validate_ninety_day_cycle_activation(),
  public.touch_ninety_day_meeting(),
  public.enroll_ninety_day_user(uuid, bigint),
  public.configure_ninety_day_cycle(bigint, text, date, text, text, bigint[], bigint, uuid),
  public.promote_ninety_day_user(uuid)
  from public, anon, authenticated;
grant execute on function public.enroll_ninety_day_user(uuid, bigint),
  public.configure_ninety_day_cycle(bigint, text, date, text, text, bigint[], bigint, uuid),
  public.promote_ninety_day_user(uuid)
  to service_role;

commit;
