begin;

create table if not exists public.system_scorecard_version_migrations (
  id bigint generated by default as identity primary key,
  business_review_id bigint not null
    references public.business_reviews (id) on delete cascade,
  from_template_key text not null
    references public.system_scorecard_templates (key) on delete restrict,
  to_template_key text not null
    references public.system_scorecard_templates (key) on delete restrict,
  migrated_by uuid null
    references public.profiles (id) on delete set null,
  resolution jsonb not null default '{}'::jsonb,
  previous_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique (business_review_id, to_template_key)
);

comment on table public.system_scorecard_version_migrations is
  'Audit trail for atomic migrations of incomplete Business Reviews between immutable Systems Scorecard versions.';

alter table public.system_scorecard_version_migrations enable row level security;
revoke all on table public.system_scorecard_version_migrations from anon, authenticated;
grant select, insert on table public.system_scorecard_version_migrations to service_role;

create or replace function public.admin_clone_system_scorecard_version(
  _source_template_key text,
  _actor_id uuid
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  _source public.system_scorecard_templates%rowtype;
  _next_version integer;
  _target_key text;
  _category record;
  _new_category_id bigint;
begin
  select template.*
    into _source
  from public.system_scorecard_templates as template
  where template.key = _source_template_key
  for update;

  if _source.key is null then
    raise exception 'Scorecard template not found.';
  end if;

  if exists (
    select 1
    from public.system_scorecard_templates as candidate
    where candidate.audience = _source.audience
      and candidate.is_active = false
      and not exists (
        select 1
        from public.business_reviews as review
        where review.system_scorecard_template_key = candidate.key
      )
  ) then
    raise exception 'This scorecard already has an unpublished draft version.';
  end if;

  select coalesce(max(template.version), 0) + 1
    into _next_version
  from public.system_scorecard_templates as template
  where template.audience = _source.audience;

  _target_key := format('%s_scorecard_v%s', _source.audience::text, _next_version);

  insert into public.system_scorecard_templates (
    key,
    audience,
    name,
    version,
    is_active,
    created_at,
    updated_at
  )
  values (
    _target_key,
    _source.audience,
    _source.name,
    _next_version,
    false,
    now(),
    now()
  );

  for _category in
    select category.*
    from public.system_scorecard_categories as category
    where category.template_key = _source.key
    order by category.position, category.id
  loop
    insert into public.system_scorecard_categories (
      template_key,
      key,
      label,
      position,
      created_at,
      updated_at
    )
    values (
      _target_key,
      _category.key,
      _category.label,
      _category.position,
      now(),
      now()
    )
    returning id into _new_category_id;

    insert into public.system_scorecard_systems (
      template_key,
      category_id,
      key,
      label,
      position,
      library_item_id,
      created_at,
      updated_at
    )
    select
      _target_key,
      _new_category_id,
      system.key,
      system.label,
      system.position,
      system.library_item_id,
      now(),
      now()
    from public.system_scorecard_systems as system
    where system.template_key = _source.key
      and system.category_id = _category.id
    order by system.position, system.id;
  end loop;

  return _target_key;
end;
$$;

comment on function public.admin_clone_system_scorecard_version(text, uuid) is
  'Creates one inactive, editable copy of a scorecard template with the next audience version number.';

create or replace function public.admin_replace_system_scorecard_draft(
  _template_key text,
  _name text,
  _categories jsonb,
  _actor_id uuid
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  _template public.system_scorecard_templates%rowtype;
  _category jsonb;
  _system jsonb;
  _category_position bigint;
  _system_position bigint;
  _category_id bigint;
  _library_item_id bigint;
begin
  select template.*
    into _template
  from public.system_scorecard_templates as template
  where template.key = _template_key
  for update;

  if _template.key is null then
    raise exception 'Scorecard template not found.';
  end if;

  if _template.is_active then
    raise exception 'Published scorecard versions are immutable.';
  end if;

  if exists (
    select 1
    from public.business_reviews as review
    where review.system_scorecard_template_key = _template.key
  ) then
    raise exception 'A scorecard version used by a Business Review is immutable.';
  end if;

  if nullif(btrim(_name), '') is null then
    raise exception 'A scorecard name is required.';
  end if;

  if _categories is null
    or jsonb_typeof(_categories) <> 'array'
    or jsonb_array_length(_categories) = 0
  then
    raise exception 'At least one scorecard category is required.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(_categories) as category(value)
    where nullif(btrim(category.value ->> 'key'), '') is null
      or nullif(btrim(category.value ->> 'label'), '') is null
      or jsonb_typeof(coalesce(category.value -> 'systems', '[]'::jsonb)) <> 'array'
      or jsonb_array_length(coalesce(category.value -> 'systems', '[]'::jsonb)) = 0
  ) then
    raise exception 'Every category needs a stable key, label, and at least one system.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(_categories) as category(value)
    group by category.value ->> 'key'
    having count(*) > 1
  ) then
    raise exception 'Category keys must be unique within a scorecard version.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(_categories) as category(value)
    cross join lateral jsonb_array_elements(category.value -> 'systems') as system(value)
    where nullif(btrim(system.value ->> 'key'), '') is null
      or nullif(btrim(system.value ->> 'label'), '') is null
  ) then
    raise exception 'Every system needs a stable key and label.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(_categories) as category(value)
    cross join lateral jsonb_array_elements(category.value -> 'systems') as system(value)
    group by system.value ->> 'key'
    having count(*) > 1
  ) then
    raise exception 'System keys must be unique within a scorecard version.';
  end if;

  delete from public.system_scorecard_systems as system
  where system.template_key = _template.key;

  delete from public.system_scorecard_categories as category
  where category.template_key = _template.key;

  for _category, _category_position in
    select item.value, item.ordinality
    from jsonb_array_elements(_categories) with ordinality as item(value, ordinality)
  loop
    insert into public.system_scorecard_categories (
      template_key,
      key,
      label,
      position,
      created_at,
      updated_at
    )
    values (
      _template.key,
      btrim(_category ->> 'key'),
      btrim(_category ->> 'label'),
      _category_position,
      now(),
      now()
    )
    returning id into _category_id;

    for _system, _system_position in
      select item.value, item.ordinality
      from jsonb_array_elements(_category -> 'systems') with ordinality as item(value, ordinality)
    loop
      _library_item_id := nullif(_system ->> 'libraryItemId', '')::bigint;

      insert into public.system_scorecard_systems (
        template_key,
        category_id,
        key,
        label,
        position,
        library_item_id,
        created_at,
        updated_at
      )
      values (
        _template.key,
        _category_id,
        btrim(_system ->> 'key'),
        btrim(_system ->> 'label'),
        _system_position,
        _library_item_id,
        now(),
        now()
      );
    end loop;
  end loop;

  update public.system_scorecard_templates as template
  set name = btrim(_name),
      updated_at = now()
  where template.key = _template.key;

  return _template.key;
end;
$$;

comment on function public.admin_replace_system_scorecard_draft(text, text, jsonb, uuid) is
  'Atomically replaces the editable structure of an unpublished and unused scorecard version.';

create or replace function public.admin_discard_system_scorecard_draft(
  _template_key text,
  _actor_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  _template public.system_scorecard_templates%rowtype;
begin
  select template.*
    into _template
  from public.system_scorecard_templates as template
  where template.key = _template_key
  for update;

  if _template.key is null then
    raise exception 'Scorecard template not found.';
  end if;

  if _template.is_active or exists (
    select 1
    from public.business_reviews as review
    where review.system_scorecard_template_key = _template.key
  ) then
    raise exception 'Only an unpublished, unused scorecard draft can be discarded.';
  end if;

  delete from public.system_scorecard_systems as system
  where system.template_key = _template.key;

  delete from public.system_scorecard_categories as category
  where category.template_key = _template.key;

  delete from public.system_scorecard_templates as template
  where template.key = _template.key;
end;
$$;

comment on function public.admin_discard_system_scorecard_draft(text, uuid) is
  'Deletes an unpublished scorecard version only while no Business Review references it.';

create or replace function public.admin_publish_system_scorecard_version(
  _template_key text,
  _actor_id uuid,
  _resolutions jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  _target public.system_scorecard_templates%rowtype;
  _review public.business_reviews%rowtype;
  _resolution jsonb;
  _snapshot jsonb;
  _priority jsonb;
  _rating jsonb;
  _old_system_key text;
  _target_system_key text;
  _target_system_id bigint;
  _target_system_label text;
  _target_library_item_id bigint;
  _starting_status public.system_scorecard_status;
  _mapped_priority_keys text[];
  _new_priority_position integer;
  _removed_priority_count integer;
  _removed_reviewed_count integer;
  _eligible_count integer := 0;
  _migrated_count integer := 0;
  _skipped_count integer := 0;
  _was_active boolean;
begin
  if jsonb_typeof(coalesce(_resolutions, '[]'::jsonb)) <> 'array' then
    raise exception 'Conflict resolutions must be an array.';
  end if;

  select template.*
    into _target
  from public.system_scorecard_templates as template
  where template.key = _template_key
  for update;

  if _target.key is null then
    raise exception 'Scorecard template not found.';
  end if;

  _was_active := _target.is_active;

  if not _target.is_active and exists (
    select 1
    from public.business_reviews as review
    where review.system_scorecard_template_key = _target.key
  ) then
    raise exception 'A retired scorecard version cannot be published again.';
  end if;

  if not exists (
    select 1
    from public.system_scorecard_systems as system
    where system.template_key = _target.key
  ) then
    raise exception 'A scorecard version must contain at least one system before publishing.';
  end if;

  for _review in
    select review.*
    from public.business_reviews as review
    join public.system_scorecard_templates as current_template
      on current_template.key = review.system_scorecard_template_key
    where review.status::text = 'draft'
      and current_template.audience = _target.audience
      and review.system_scorecard_template_key <> _target.key
    order by review.review_date, review.id
    for update of review
  loop
    _eligible_count := _eligible_count + 1;

    select count(*)::integer
      into _removed_priority_count
    from public.business_review_system_priorities as priority
    join public.system_scorecard_systems as old_system
      on old_system.id = priority.system_id
    left join public.system_scorecard_systems as target_system
      on target_system.template_key = _target.key
      and target_system.key = old_system.key
    where priority.business_review_id = _review.id
      and target_system.id is null;

    select count(*)::integer
      into _removed_reviewed_count
    from public.business_review_system_ratings as rating
    join public.system_scorecard_systems as old_system
      on old_system.id = rating.system_id
    left join public.system_scorecard_systems as target_system
      on target_system.template_key = _target.key
      and target_system.key = old_system.key
    where rating.business_review_id = _review.id
      and rating.reviewed_at is not null
      and target_system.id is null;

    _resolution := null;
    select item.value
      into _resolution
    from jsonb_array_elements(coalesce(_resolutions, '[]'::jsonb)) as item(value)
    where (item.value ->> 'reviewId')::bigint = _review.id
    limit 1;

    if _removed_priority_count > 0 or _removed_reviewed_count > 0 then
      if _resolution is null
        or coalesce(_resolution ->> 'action', '') not in ('upgrade', 'skip')
      then
        raise exception 'Business Review % has unresolved scorecard conflicts.', _review.id;
      end if;

      if _resolution ->> 'action' = 'skip' then
        _skipped_count := _skipped_count + 1;
        continue;
      end if;

      if _removed_reviewed_count > 0
        and not coalesce((_resolution ->> 'confirmReviewedRemoval')::boolean, false)
      then
        raise exception 'Business Review % contains reviewed systems that require confirmation.', _review.id;
      end if;
    else
      _resolution := jsonb_build_object(
        'reviewId', _review.id,
        'action', 'automatic'
      );
    end if;

    select jsonb_build_object(
      'review', to_jsonb(_review),
      'ratings', coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'systemKey', system.key,
            'status', rating.status,
            'reviewedAt', rating.reviewed_at,
            'reviewedBy', rating.reviewed_by,
            'updatedBy', rating.updated_by,
            'createdAt', rating.created_at,
            'updatedAt', rating.updated_at
          )
          order by system.position, system.id
        )
        from public.business_review_system_ratings as rating
        join public.system_scorecard_systems as system
          on system.id = rating.system_id
        where rating.business_review_id = _review.id
      ), '[]'::jsonb),
      'priorities', coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'systemKey', system.key,
            'position', priority.position,
            'actionStepId', priority.action_step_id,
            'startingStatus', priority.starting_status,
            'selectedAt', priority.selected_at,
            'selectedBy', priority.selected_by
          )
          order by priority.position, system.id
        )
        from public.business_review_system_priorities as priority
        join public.system_scorecard_systems as system
          on system.id = priority.system_id
        where priority.business_review_id = _review.id
      ), '[]'::jsonb)
    ) into _snapshot;

    _mapped_priority_keys := array[]::text[];

    for _priority in
      select item.value
      from jsonb_array_elements(_snapshot -> 'priorities') as item(value)
    loop
      _old_system_key := _priority ->> 'systemKey';
      _target_system_key := _old_system_key;
      _target_system_id := null;

      select system.id
        into _target_system_id
      from public.system_scorecard_systems as system
      where system.template_key = _target.key
        and system.key = _target_system_key
      limit 1;

      if _target_system_id is null then
        if not (
          coalesce(_resolution -> 'priorityReplacements', '{}'::jsonb) ? _old_system_key
        ) then
          raise exception 'Priority % in Business Review % needs a replacement or explicit removal.',
            _old_system_key, _review.id;
        end if;

        _target_system_key := _resolution -> 'priorityReplacements' ->> _old_system_key;

        if _target_system_key is not null then
          select system.id
            into _target_system_id
          from public.system_scorecard_systems as system
          where system.template_key = _target.key
            and system.key = _target_system_key
          limit 1;

          if _target_system_id is null then
            raise exception 'Replacement system % was not found in %.',
              _target_system_key, _target.key;
          end if;
        end if;
      end if;

      if _target_system_key is not null
        and _target_system_key = any(_mapped_priority_keys)
      then
        raise exception 'Business Review % would contain the same priority twice.', _review.id;
      end if;

      if _target_system_key is not null then
        _mapped_priority_keys := array_append(_mapped_priority_keys, _target_system_key);
      end if;
    end loop;

    delete from public.business_review_system_priorities as priority
    where priority.business_review_id = _review.id;

    delete from public.business_review_system_ratings as rating
    where rating.business_review_id = _review.id;

    update public.business_reviews as review
    set system_scorecard_template_key = _target.key,
        updated_at = now()
    where review.id = _review.id;

    insert into public.business_review_system_ratings (
      business_review_id,
      template_key,
      system_id,
      status,
      reviewed_at,
      reviewed_by,
      updated_by,
      created_at,
      updated_at
    )
    select
      _review.id,
      _target.key,
      target_system.id,
      coalesce(
        (source_rating.value ->> 'status')::public.system_scorecard_status,
        'not_started'::public.system_scorecard_status
      ),
      nullif(source_rating.value ->> 'reviewedAt', '')::timestamptz,
      nullif(source_rating.value ->> 'reviewedBy', '')::uuid,
      nullif(source_rating.value ->> 'updatedBy', '')::uuid,
      coalesce(
        nullif(source_rating.value ->> 'createdAt', '')::timestamptz,
        now()
      ),
      coalesce(
        nullif(source_rating.value ->> 'updatedAt', '')::timestamptz,
        now()
      )
    from public.system_scorecard_systems as target_system
    left join lateral (
      select item.value
      from jsonb_array_elements(_snapshot -> 'ratings') as item(value)
      where item.value ->> 'systemKey' = target_system.key
      limit 1
    ) as source_rating on true
    where target_system.template_key = _target.key;

    _new_priority_position := 0;

    for _priority in
      select item.value
      from jsonb_array_elements(_snapshot -> 'priorities') as item(value)
      order by (item.value ->> 'position')::integer
    loop
      _old_system_key := _priority ->> 'systemKey';
      _target_system_key := _old_system_key;
      _target_system_id := null;

      select system.id, system.label, system.library_item_id
        into _target_system_id, _target_system_label, _target_library_item_id
      from public.system_scorecard_systems as system
      where system.template_key = _target.key
        and system.key = _target_system_key
      limit 1;

      if _target_system_id is null then
        _target_system_key := _resolution -> 'priorityReplacements' ->> _old_system_key;

        if _target_system_key is not null then
          select system.id, system.label, system.library_item_id
            into _target_system_id, _target_system_label, _target_library_item_id
          from public.system_scorecard_systems as system
          where system.template_key = _target.key
            and system.key = _target_system_key
          limit 1;
        end if;
      end if;

      if _target_system_id is null then
        delete from public.coaching_note_action_steps as action_step
        where action_step.id = (_priority ->> 'actionStepId')::bigint;
        continue;
      end if;

      _new_priority_position := _new_priority_position + 1;

      if _target_system_key = _old_system_key then
        _starting_status := (_priority ->> 'startingStatus')::public.system_scorecard_status;
      else
        select rating.status
          into _starting_status
        from public.business_review_system_ratings as rating
        where rating.business_review_id = _review.id
          and rating.system_id = _target_system_id;
      end if;

      insert into public.business_review_system_priorities (
        business_review_id,
        system_id,
        position,
        action_step_id,
        starting_status,
        selected_at,
        selected_by
      )
      values (
        _review.id,
        _target_system_id,
        _new_priority_position,
        (_priority ->> 'actionStepId')::bigint,
        _starting_status,
        coalesce(nullif(_priority ->> 'selectedAt', '')::timestamptz, now()),
        nullif(_priority ->> 'selectedBy', '')::uuid
      );

      update public.coaching_note_action_steps as action_step
      set label = _target_system_label,
          library_item_id = _target_library_item_id,
          updated_at = now()
      where action_step.id = (_priority ->> 'actionStepId')::bigint;
    end loop;

    insert into public.system_scorecard_version_migrations (
      business_review_id,
      from_template_key,
      to_template_key,
      migrated_by,
      resolution,
      previous_snapshot
    )
    values (
      _review.id,
      _review.system_scorecard_template_key,
      _target.key,
      _actor_id,
      _resolution,
      _snapshot
    );

    _migrated_count := _migrated_count + 1;
  end loop;

  if not _was_active then
    update public.system_scorecard_templates as template
    set is_active = false,
        updated_at = now()
    where template.audience = _target.audience
      and template.key <> _target.key
      and template.is_active = true;

    update public.system_scorecard_templates as template
    set is_active = true,
        updated_at = now()
    where template.key = _target.key;
  end if;

  return jsonb_build_object(
    'templateKey', _target.key,
    'published', not _was_active,
    'eligibleReviewCount', _eligible_count,
    'migratedReviewCount', _migrated_count,
    'skippedReviewCount', _skipped_count
  );
end;
$$;

comment on function public.admin_publish_system_scorecard_version(text, uuid, jsonb) is
  'Publishes a scorecard version and atomically upgrades compatible draft reviews, requiring explicit resolutions for removed priorities or reviewed systems.';

revoke all on function public.admin_clone_system_scorecard_version(text, uuid) from public, anon, authenticated;
revoke all on function public.admin_replace_system_scorecard_draft(text, text, jsonb, uuid) from public, anon, authenticated;
revoke all on function public.admin_discard_system_scorecard_draft(text, uuid) from public, anon, authenticated;
revoke all on function public.admin_publish_system_scorecard_version(text, uuid, jsonb) from public, anon, authenticated;

grant execute on function public.admin_clone_system_scorecard_version(text, uuid) to service_role;
grant execute on function public.admin_replace_system_scorecard_draft(text, text, jsonb, uuid) to service_role;
grant execute on function public.admin_discard_system_scorecard_draft(text, uuid) to service_role;
grant execute on function public.admin_publish_system_scorecard_version(text, uuid, jsonb) to service_role;

commit;
