begin;

create table if not exists public.user_training_assignments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_node_id bigint not null references public.content_nodes(id) on delete restrict,
  coaching_note_id bigint not null references public.coaching_notes_base(id) on delete cascade,
  assigned_by uuid references public.profiles(id) on delete set null,
  assigned_at timestamptz not null default now(),
  context_label text,
  due_at timestamptz,
  ended_at timestamptz,
  ended_by uuid references public.profiles(id) on delete set null,
  constraint user_training_assignments_context_label_length
    check (context_label is null or char_length(context_label) <= 240),
  constraint user_training_assignments_ended_after_assignment
    check (ended_at is null or ended_at >= assigned_at)
);

comment on table public.user_training_assignments is
  'A course explicitly assigned to a member for one coaching-note / 60-day cycle.';
comment on column public.user_training_assignments.context_label is
  'Optional member-facing timing note, for example "Before the next session".';

create unique index if not exists user_training_assignments_one_active_per_cycle
  on public.user_training_assignments (user_id, coaching_note_id)
  where ended_at is null;

create index if not exists user_training_assignments_member_history
  on public.user_training_assignments (user_id, assigned_at desc);

create index if not exists user_training_assignments_course_active
  on public.user_training_assignments (course_node_id, user_id)
  where ended_at is null;

create or replace function public.validate_user_training_assignment()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.coaching_notes_base as note
    where note.id = new.coaching_note_id
      and note.user_id = new.user_id
  ) then
    raise exception 'The coaching note does not belong to this member.'
      using errcode = '23514';
  end if;

  if not exists (
    select 1
    from public.content_nodes as node
    where node.id = new.course_node_id
      and node.node_type::text = 'course'
      and node.state::text = 'published'
  ) then
    raise exception 'Assigned training must be a published course.'
      using errcode = '23514';
  end if;

  new.context_label := nullif(btrim(new.context_label), '');
  return new;
end;
$$;

drop trigger if exists validate_user_training_assignment
  on public.user_training_assignments;
create trigger validate_user_training_assignment
before insert or update of user_id, course_node_id, coaching_note_id, context_label
on public.user_training_assignments
for each row
execute function public.validate_user_training_assignment();

-- Assignment and catalogue visibility are separate concepts. This grant is a
-- one-way safety net so assigning a limited course always makes it openable.
-- Ending an assignment intentionally does not revoke a pre-existing or
-- assignment-created grant: removing a task should never unexpectedly remove
-- material the member could already use.
create or replace function public.grant_assigned_training_access()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_course_visibility (user_id, course_node_id)
  values (new.user_id, new.course_node_id)
  on conflict (user_id, course_node_id) do nothing;

  return new;
end;
$$;

drop trigger if exists grant_assigned_training_access
  on public.user_training_assignments;
create trigger grant_assigned_training_access
after insert on public.user_training_assignments
for each row
execute function public.grant_assigned_training_access();

create or replace function public.set_user_training_assignment(
  p_user_id uuid,
  p_coaching_note_id bigint,
  p_course_node_id bigint,
  p_assigned_by uuid,
  p_context_label text default null,
  p_due_at timestamptz default null
)
returns public.user_training_assignments
language plpgsql
security definer
set search_path = public
as $$
declare
  current_assignment public.user_training_assignments;
  saved_assignment public.user_training_assignments;
begin
  perform pg_advisory_xact_lock(
    hashtextextended(p_user_id::text || ':' || p_coaching_note_id::text, 0)
  );

  select assignment.*
  into current_assignment
  from public.user_training_assignments as assignment
  where assignment.user_id = p_user_id
    and assignment.coaching_note_id = p_coaching_note_id
    and assignment.ended_at is null
  for update;

  if current_assignment.id is not null
     and current_assignment.course_node_id = p_course_node_id then
    update public.user_training_assignments
    set context_label = nullif(btrim(p_context_label), ''),
        due_at = p_due_at
    where id = current_assignment.id
    returning * into saved_assignment;

    insert into public.user_course_visibility (user_id, course_node_id)
    values (p_user_id, p_course_node_id)
    on conflict (user_id, course_node_id) do nothing;

    return saved_assignment;
  end if;

  update public.user_training_assignments
  set ended_at = now(),
      ended_by = p_assigned_by
  where user_id = p_user_id
    and coaching_note_id = p_coaching_note_id
    and ended_at is null;

  insert into public.user_training_assignments (
    user_id,
    course_node_id,
    coaching_note_id,
    assigned_by,
    context_label,
    due_at
  )
  values (
    p_user_id,
    p_course_node_id,
    p_coaching_note_id,
    p_assigned_by,
    nullif(btrim(p_context_label), ''),
    p_due_at
  )
  returning * into saved_assignment;

  return saved_assignment;
end;
$$;

create or replace function public.end_user_training_assignment(
  p_user_id uuid,
  p_coaching_note_id bigint,
  p_ended_by uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  changed_count integer;
begin
  perform pg_advisory_xact_lock(
    hashtextextended(p_user_id::text || ':' || p_coaching_note_id::text, 0)
  );

  update public.user_training_assignments
  set ended_at = now(),
      ended_by = p_ended_by
  where user_id = p_user_id
    and coaching_note_id = p_coaching_note_id
    and ended_at is null;

  get diagnostics changed_count = row_count;
  return changed_count > 0;
end;
$$;

alter table public.user_training_assignments enable row level security;

revoke all on table public.user_training_assignments from anon, authenticated;
grant select, insert, update on table public.user_training_assignments to service_role;
grant usage, select on sequence public.user_training_assignments_id_seq to service_role;

revoke all on function public.set_user_training_assignment(uuid, bigint, bigint, uuid, text, timestamptz)
  from public, anon, authenticated;
revoke all on function public.end_user_training_assignment(uuid, bigint, uuid)
  from public, anon, authenticated;
grant execute on function public.set_user_training_assignment(uuid, bigint, bigint, uuid, text, timestamptz)
  to service_role;
grant execute on function public.end_user_training_assignment(uuid, bigint, uuid)
  to service_role;

commit;
